module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: 'USER_DETAIL',
        TICKET_ADD_NEW: 'TICKET_ADD_NEW',
        HOTEL_ADD_NEW: 'HOTEL_ADD_NEW',
        LEAD_ADD_NEW: 'LEAD_ADD_NEW',
        CONFIRMATION: 'CONFIRMATION',
        DEFAULT: '',
    },

    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: 'NOTIFICATION',
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        LEAD_DELETE: 'LEAD_DELETE',
        TICKET_DELETE: 'TICKET_DELETE',
    },
})
